### ISSUE TITLE
Feature: include `LICENSE.md` to denote a license for this project

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/repo-query#5]
### Type of feature

🍕 Feature

### Current behavior

There's currently no license or attribution.

### Suggested solution

We'll need a license before we merge in #1 - cc @bdougie for your preference of license on this project. My gut is probably a permissive MIT license since we'll be using other open source, permissive ML models.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Yes, MIT is ideal since we don't own a trademark on repo-query which is why we'd want to do Apache. The alternative is [ISC](https://github.com/open-sauced/catsup/blob/main/LICENSE), which we use in [catsup](https://github.com/open-sauced/catsup/). But MIT is fine. 

One thing I wanted to ask but I haven't dug in. Are we omitting projects that don't have a license or a permissable license at least? If not, we should track that as a needed launch feature.

**Comment by jpmcb** [comment]
> Are we omitting projects that don't have a license or a permissable license at least? If not, we should track that as a needed launch feature.

Good question: I don't believe so. Certain files are ignored (like `node_modules`, etc.) but we'll need to add the feature to ignore repos that do not have a permissible license. I'll make an issue for that.
